# Generated by Django 6.0.5 on 2026-06-07 09:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "name",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("subject", models.TextField()),
                ("text", models.TextField()),
                ("html", models.TextField()),
                ("raw", models.TextField(default="")),
                ("no_reply", models.BooleanField(default=True)),
                (
                    "bcc",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                    ),
                ),
            ],
            options={
                "verbose_name": "Backbone email template",
                "verbose_name_plural": "Backbone email templates",
            },
        ),
    ]
